version: '3.9'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-production}
    ports:
      - '4002:4000'
    env_file:
      - .env
    depends_on:
      - cache

  app2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-production}
    ports:
      - '4003:4000'
    env_file:
      - .env
    depends_on:
      - cache

  app3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-production}
    ports:
      - '4004:4000'
    env_file:
      - .env
    depends_on:
      - cache

  redis-master1:
    build:
      context: .
      dockerfile: Dockerfile.redis
    environment:
      - REDIS_ROLE=master
    ports:
      - "6380:6379"

  redis-master2:
    build:
      context: .
      dockerfile: Dockerfile.redis
    environment:
      - REDIS_ROLE=master
    ports:
      - "6381:6379"

  redis-master3:
    build:
      context: .
      dockerfile: Dockerfile.redis
    environment:
      - REDIS_ROLE=master
    ports:
      - "6382:6379"

  # cache is used if want to simulate single node redis architecture
  cache:
    image: redis:7.2-alpine
    command: redis-server --maxmemory 100mb --maxmemory-policy volatile-lru --loglevel debug
    ports:
      - '6379:6379'

  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3
