# Global Prometheus configuration
global:
  scrape_interval: 15s # How often to scrape targets
  evaluation_interval: 15s # How often to evaluate alerting rules (if any)

# Scrape configurations: Defines targets to monitor
scrape_configs:
  # Job definition for scraping the socket server application instances
  - job_name: 'socket-server'
    # Use Docker's internal DNS to find the services defined in docker-compose.yml
    # Prometheus will automatically try to scrape the '/metrics' endpoint on these targets.
    static_configs:
      - targets:
          - 'app1:4000' # Service name 'app1' on internal port 4000
          - 'app2:4000' # Service name 'app2' on internal port 4000
          - 'app3:4000' # Service name 'app3' on internal port 4000 