name: Publish Release

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight (UTC)

jobs:
  update-examples:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - name: Update examples
        run: bash ./scripts/update-sdk-examples.sh

